repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-vcs-permalinks # Ensures that links to vcs websites are permalinks.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: detect-aws-credentials # Detects *your* aws credentials from the aws cli credentials file
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: forbid-new-submodules # Prevent addition of new git submodules
      - id: mixed-line-ending # Replaces or checks mixed line ending
      - id: no-commit-to-branch # Don't commit to branch
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.52.0
    hooks:
      - id: checkov  # Runs checkov on Terraform templates.
      - id: terraform_docs  # Inserts input and output documentation into README.md (using terraform-docs).
    #   - id: terraform_docs  # Inserts input and output documentation into README.md (using terraform-docs).
    #     name: terraform_docs examples/simple
    #     files: examples/simple
      - id: terraform_fmt # Rewrites all Terraform configuration files to a canonical format.
      - id: terraform_providers_lock # Updates provider signatures in dependency lock files.
      - id: terraform_tflint # Validates all Terraform configuration files with TFLint.
      - id: terraform_tfsec # Static analysis of Terraform templates to spot potential security issues.
      - id: terraform_validate # Validates all Terraform configuration files.
      # - id: terrascan # Runs terrascan on Terraform templates. (Optional)

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen # Check whether the commit message follows commiting rules
        stages:
          - commit-msg

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc # Insert a table of contents in Markdown files, like a README.md
