name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
     branches:
      - main

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Login to AWS ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Build Docker image
        run: |
          docker build -t valheim-dedicated:latest .
          docker tag valheim-dedicated:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/valheim-dedicated:latest

      - name: Tag and push Docker image to ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag valheim-dedicated:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/valheim-dedicated:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/valheim-dedicated:latest
